// src/react/views/AppProvider.tsx
import * as React from 'react'
import { Store } from 'redux'
import { Provider } from 'react-redux'
import { StoreST } from '../store'
import { TodosContainer } from './TodosContainer'
import { TodosFormContainer } from './TodosFormContainer'
import { TodosItemsContainer } from './TodosItemsContainer'
import { SummaryContainer } from './SummaryContainer'
import styled from 'styled-components'

// ______________________________________________________

export class AppProvider extends React.Component<
  { store: Store<StoreST> },
  never
> {
  render() {
    return (
      <Provider store={this.props.store}>
        <StyledView>
          <TodosContainer
            items={() => <TodosItemsContainer />}
            form={() => <TodosFormContainer />}
          />
          <SummaryContainer />
        </StyledView>
      </Provider>
    )
  }
}

const StyledView = styled.div`
  padding: 10px;
  box-sizing: border-box;
  > * {
    margin-bottom: 10px;
  }
`

// src/vue/views/AppProvider.vue
<template>
  <div class='root'>
    <todos-vue />
  </div>
</template>


<script lang='ts'>
import Vue from 'vue'
import TodosVue from './Todos.vue'
const components = { TodosVue }
</script>


<style scoped>
.root {
  padding: 10px;
  box-sizing: border-box;
}
.root > * {
  margin-bottom: 10px;
}
</style>
