// src/vue/views/Summary.vue
<template>
  <div class='summary'>
    <p>{{dateLabel}}</p>
    <p>{{todosCountStatusLabel}}</p>
    <p>{{bounderyOutsideCountLabel}}</p>
  </div>
</template>


<script lang='ts'>
import Vue from 'vue'
import * as Todos from '../models/Todos'
import * as Summary from '../models/Summary'
const computed = {
  ...Todos.mapGetters({
    todosCountStatusLabel: 'getTodosCountStatusLabel'
  }),
  ...Summary.mapGetters({
    dateLabel: 'getDateLabel',
    bounderyOutsideCountLabel: 'getBounderyOutsideCountLabel'
  })
}

export default Vue.extend({ computed })
</script>


<style scoped>
.summary {
  padding: 20px;
  border-radius: 5px;
  border: 2px solid;
}
.summary > p {
  margin: 5px;
  font-size: 12px;
}
</style>

// src/react/views/SummaryComponent.tsx
import * as React from 'react'
import styled from 'styled-components'
import { MapState } from './SummaryContainer'

// ______________________________________________________
//
// @ Types

interface Props extends MapState {
  className?: string
  children?: React.ReactChild
}

// ______________________________________________________
//
// @ View

const View = (props: Props) => (
  <div className={props.className}>
    <p>{props.dateLabel}</p>
    <p>{props.todosCountStatusLabel}</p>
    <p>{props.bounderyOutsideCountLabel}</p>
  </div>
)

// ______________________________________________________
//
// @ StyledView

export default styled(View)`
  padding: 20px;
  border-radius: 5px;
  border: 2px solid;
  > p {
    margin: 5px;
    font-size: 12px;
  }
`
