// src/vue/views/TodosItems.vue
<template>
  <div>
    <ul class="items">
      <li
        class="item"
        v-bind:class="{ disabled: todo.done }"
        v-bind:key="todo.id"
        v-for="todo in todos"
      >
        <p class="button">
          <button
            v-on:click="handleClickDone({ id: todo.id, done: true })"
            v-bind:disabled="todo.done"
          >done</button>
        </p>
        <p class="value">{{todo.value}}</p>
        <p class="dateLabel">{{todo.dateLabel}}</p>
      </li>
    </ul>
  </div>
</template>


<script lang='ts'>
import Vue from 'vue'
import * as Todos from '../models/Todos'
const computed = {
  ...Todos.mapGetters({
    todos: 'getVisibleItems'
  })
}
const methods = {
  ...Todos.mapMutations({
    handleClickDone: 'setItemDone'
  })
}
export default Vue.extend({ computed, methods })
</script>


<style scoped>
.items {
  padding: 0;
}
.item {
  display: flex;
  justify-content: space-around;
  margin-bottom: 3px;
  list-style: none;
  font-size: 12px;
}
.item.disabled {
  color: #eee;
}
.item > .button {
  margin: 0px;
}
.item > .value {
  flex: 1 0 auto;
  margin: 0 0 0 10px;
}
.item > .dateLabel {
  margin: 0px;
}
</style>

// src/react/views/TodosItemsComponent.tsx
import * as React from 'react'
import styled from 'styled-components'
import TodoItem from './TodoItem'
import { MapState, MapDispatch } from './TodosItemsContainer'

// ______________________________________________________
//
// @ Types

type Props = MapState &
  MapDispatch & {
    className?: string
    children?: React.ReactChild
  }

// ______________________________________________________
//
// @ View

const View = (props: Props) => (
  <ul className={props.className}>
    {props.items.map(todo => (
      <TodoItem
        key={todo.id}
        id={todo.id}
        value={todo.value}
        done={todo.done}
        dateLabel={todo.dateLabel}
        handleClickDone={props.handleClickDone}
      />
    ))}
  </ul>
)

// ______________________________________________________
//
// @ StyledView

export default styled(View)`
  padding: 0;
  > li {
    margin-bottom: 3px;
    list-style: none;
    font-size: 12px;
  }
`
