// src/vue/views/Todos.vue
<template>
  <div class='todos'>
    <h1>{{name}}</h1>
    <p>{{dateLabel}}</p>
    <p>{{todosCountStatusLabel}}</p>
    <p>{{bounderyOutsideCountLabel}}</p>
    <p>
      <button v-on:click="handleClickToggle">
        {{toggleVisibleItemsBtnLabel}}
      </button>
    </p>
    <todos-form />
    <todos-items />
  </div>
</template>


<script lang='ts'>
import Vue from 'vue'
import TodosForm from './TodosForm.vue'
import TodosItems from './TodosItems.vue'
import * as Timer from '../models/Timer'
import * as Todos from '../models/Todos'
const computed = {
  ...Timer.mapState({
    dateLabel: 'dateLabel'
  }),
  ...Todos.mapState({
    name: 'name',
    inputValue: 'input'
  }),
  ...Todos.mapGetters({
    todosCountStatusLabel: 'getTodosCountStatusLabel',
    toggleVisibleItemsBtnLabel: 'getToggleVisibleItemsBtnLabel',
    bounderyOutsideCountLabel: 'getBounderyOutsideCountLabel'
  })
}
const methods = {
  ...Todos.mapMutations({
    handleClickToggle: 'toggleShowAll'
  })
}
const components = {
  TodosForm,
  TodosItems
}
export default Vue.extend({ computed, methods, components })
</script>


<style>
.todos {
  padding: 20px;
  border-radius: 5px;
  border: 2px solid;
}
.todos > h1 {
  margin-bottom: 10px;
  font-size: 2rem;
  font-weight: bolder;
}
.todos > p {
  margin-bottom: 10px;
}
</style>

// src/react/views/TodosComponent.tsx
import * as React from 'react'
import styled from 'styled-components'
import { MapState, MapDispatch, OwnProps } from './TodosContainer'

// ______________________________________________________
//
// @ Types

interface Props extends MapState, MapDispatch, OwnProps {
  className?: string
  children?: React.ReactChild
}

// ______________________________________________________
//
// @ View

const View = (props: Props) => (
  <div className={props.className}>
    <h1>{props.name}</h1>
    <p>{props.dateLabel}</p>
    <p>{props.todosCountStatusLabel}</p>
    <p>{props.bounderyOutsideCountLabel}</p>
    <p>
      <button onClick={() => props.handleClickToggle()}>
        {props.toggleVisibleItemsBtnLabel}
      </button>
    </p>
    {props.form()}
    {props.items()}
  </div>
)

// ______________________________________________________
//
// @ StyledView

export default styled(View)`
  padding: 20px;
  border-radius: 5px;
  border: 2px solid;
  background-color: ${props => props.bgColor};
  > h1 {
    margin-bottom: 10px;
    font-size: 2rem;
    font-weight: bolder;
  }
  > p {
    margin-bottom: 10px;
  }
`
